### ISSUE TITLE
Archetypes not working from theme

### ISSUE THREAD

**Issue by isaaki** [spf13/hugo#533]
Archetypes are working from my project root, but not from themes. 

For getting them to work from my project root I had to add empty line returns (similar to the workaround here: https://github.com/spf13/hugo/issues/359). 

Ideas?

**Comment by tatsushid** [comment]
If it's caused by the same reason of #359, it's also the same with #776

**Comment by bjornerik** [comment]
Should be fixed by #785

**Comment by Asday** [comment]
I still have the issue on hugo 0.19 and `master`.  I've created a repository [here](https://github.com/Asday/hugo-theme-archetype-issue).

**Comment by kva1966** [comment]
Me too, I'm compiling from source via go get.

**Comment by Asday** [comment]
Fixed in 0.20, this issue can now be clos...  Oh.
